[build-system]
requires = ["hatchling>=1.27.0", "versioningit"]
build-backend = "hatchling.build"

[project]
name = "vsview"
dynamic = ["version"]
description = "The next-generation VapourSynth previewer"
readme = "README.md"
license = "EUPL-1.2 AND (MIT AND Apache-2.0 AND ISC AND OFL-1.1)"
license-files = [
    "LICENSE",
    "src/vsview/assets/icons/phosphor/LICENSE",
    "src/vsview/assets/icons/material/LICENSE",
    "src/vsview/assets/icons/lucide/LICENSE",
    "src/vsview/assets/fonts/Cascadia_Mono/LICENSE.txt",
]
requires-python = ">=3.12"
authors = [{ name = "Vardë", email = "ichunjo.le.terrible@gmail.com" }]
maintainers = [
    { name = "Vardë", email = "ichunjo.le.terrible@gmail.com" },
    { name = "Jaded Encoding Thaumaturgy", email = "jaded.encoding.thaumaturgy@gmail.com" },
]
keywords = [
    "video",
    "video-processing",
    "encoding",
    "previewer",
    "viewer",
    "vapoursynth",
    "vapoursynth-editor",
    "vapoursynth-preview",
]
classifiers = [
    "Topic :: Multimedia :: Graphics",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: ISC License (ISCL)",
    "License :: OSI Approved :: SIL Open Font License 1.1 (OFL-1.1)",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
dependencies = [
    "vapoursynth>=69",
    "vsjetengine>=1.2.0",
    "vspackrgb>=1.0.0",
    "pyside6==6.10.2",
    "jetpytools>=2.2.2",
    "pydantic>=2.0.0",
    "platformdirs>=4.9.2",
    "typer>=0.20.0",
    "pygments>=2.19.0",
    "pluggy>=1.6.0",
    "typing_extensions>=4.15.0; python_version<'3.13'",
]

[dependency-groups]
dev = [
    "hatchling>=1.27.0",
    "vsstubs>=1.0.2; python_version>='3.13'",
    "mypy>=1.19.0, <1.20.0",
    "ruff>=0.15.0, <0.16.0",
    "objgraph>=3.6.2",
    "graphviz>=0.21",
    "cython>=3.0.0",
    "types-pygments>=2.19.0.20251121",
    { include-group = "test" },
    { include-group = "plugins" },
    # "PyKDDockWidgetsQt6; sys_platform == 'win32'",
]
test = [
    "pytest>=9.0.0, <10.0.0",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.0",
    "pytest-qt>=4.5.0",
    "pytest-xvfb>=3.1.1",
]
doc = ["mkdocstrings[python]>=1.0.3", "zensical==0.0.28", "ruff"]
plugins = [
    "vsview-split-planes",
    "vsview-fftspectrum",
    "vsview-frameprops-extended",
    "vsview-audio-convert",
    "vsview-comp",
    "vsview-nativeres",
]

[project.scripts]
vsview = "vsview.cli:app"

[project.optional-dependencies]
essential = ["vsview-split-planes", "vsview-frameprops-extended", "vsview-comp"]
secrets = ["keyring>=25.7.0"]

[project.urls]
Documentation = "https://jaded-encoding-thaumaturgy.github.io/vs-view/"
Plugins = "https://jaded-encoding-thaumaturgy.github.io/vs-view/plugins/"
"Source Code" = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-view"
"Bug Tracker" = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-view/issues"
"Contact" = "https://discord.gg/XTpc6Fa9eB"

[tool.hatch.build.targets.sdist]
only-include = [
    "docs",
    "scripts",
    "src/vsview",
    "stubs",
    "tests",
    ".gitmodules",
]

[tool.hatch.build.targets.wheel]
packages = ["src/vsview"]
exclude = ["README.md", "__main__.py"]

[tool.hatch.build.targets.wheel.hooks.custom]
path = "scripts/build/hatch_hooks.py"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.vcs]
match = ["vsview/v*"]
default-tag = "vsview/v0.0.0"

[tool.versioningit.tag2version]
rmprefix = "vsview/v"

[tool.uv.workspace]
members = ["src/vspackrgb", "src/plugins/*"]

[tool.uv.sources]
vspackrgb = { workspace = true }
vsview-fftspectrum = { workspace = true }
vsview-split-planes = { workspace = true }
vsview-frameprops-extended = { workspace = true }
vsview-audio-convert = { workspace = true }
vsview-comp = { workspace = true }
# PyKDDockWidgetsQt6 = [
#     { path = "opt/pykddockwidgetsqt6-2.4.0-cp312-abi3-win_amd64.whl", marker = "sys_platform == 'win32'" },
#     # { path = "opt/pykddockwidgetsqt6-2.4.0-cp312-abi3-manylinux_2_28_x86_64.whl", marker = "sys_platform == 'linux'" },
#     # { path = "opt/pykddockwidgetsqt6-2.4.0-cp312-abi3-macosx_11_0_arm64.whl", marker = "sys_platform == 'darwin' and platform_machine == 'arm64'" },
#     # { path = "opt/pykddockwidgetsqt6-2.4.0-cp312-abi3-macosx_10_9_x86_64.whl", marker = "sys_platform == 'darwin' and platform_machine == 'x86_64'" },
# ]
# AMD64

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
exclude = ["src/kddockwidgets/"]
exclude_gitignore = true

# Flags changed by --strict
warn_return_any = false
extra_checks = false

# Misc
warn_unreachable = true

allow_redefinition_new = true
local_partial_types = true
implicit_reexport = false
strict = true

show_column_numbers = true
pretty = true
color_output = true
error_summary = true

[[tool.mypy.overrides]]
module = "vapoursynth.*"
ignore_errors = true

[tool.ruff]
line-length = 120
exclude = ["src/kddockwidgets"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
exclude = ["stubs/vapoursynth/*"]
extend-select = [
    "YTT",
    "ASYNC",
    "C4",
    "LOG",
    "G",
    "PIE",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SIM",
    "I",
    "N",
    "PERF",
    "E",
    "W",
    "UP",
    "FURB",
    "RUF",
]
ignore = ["N802", "N815"]

[tool.ruff.lint.per-file-ignores]
"__init__.*" = ["F401", "F403"]
