[build-system]
requires = [
    "hatchling",
    "hatch-rs @ git+https://github.com/Varde-s-Forks/hatch-rs.git",
    "versioningit",
]
build-backend = "hatchling.build"

[project]
name = "vspackrgb"
dynamic = ["version"]
description = "RGB packing for VapourSynth frames"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["vapoursynth", "rgb", "packing", "rust", "arm", "arm64", "aarch64"]
requires-python = ">=3.12"
authors = [{ name = "Vardë", email = "ichunjo.le.terrible@gmail.com" }]
maintainers = [
    { name = "Vardë", email = "ichunjo.le.terrible@gmail.com" },
    { name = "Jaded Encoding Thaumaturgy", email = "jaded.encoding.thaumaturgy@gmail.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Free Threading",
    "Programming Language :: Rust",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Typing :: Typed",
]
dependencies = ["vapoursynth"]

[project.optional-dependencies]
numpy = ["numpy>=2.0.0"]
numba = ["numba>=0.62.1", "numpy>=2.0.0"]

[project.urls]
"Documentation" = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-view/tree/main/src/vspackrgb"
"Source Code" = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-view/tree/main/src/vspackrgb"
"Bug Tracker" = "https://github.com/Jaded-Encoding-Thaumaturgy/vs-view/issues"
"Contact" = "https://discord.gg/XTpc6Fa9eB"

[dependency-groups]
dev = ["pytest>=9.0.0, <10.0.0", "rich>=15.0.0", "vsjetengine>=1.8.0"]
bench = ["vapoursynth-akarin>=1.5.0", "vapoursynth-vszip>=22.1.0"]

[tool.hatch.build.targets.wheel]
packages = ["src/vspackrgb"]
exclude = ["rust", "target"]

[tool.hatch.build.hooks.hatch-rs]
verbose = true
abi3 = true
path = "."
module = "vspackrgb"
target-dir = "target"

[[tool.hatch.build.hooks.hatch-rs.artifacts]]
name = "rust"
manifest = "rust/Cargo.toml"
destination = "src/vspackrgb/{python_extension_name}"
editable-debug = false

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.vcs]
match = ["vspackrgb/v*"]
default-tag = "vspackrgb/v0.0.0"

[tool.versioningit.tag2version]
rmprefix = "vspackrgb/v"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{next_version}+dirty"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.dirty"

[tool.cibuildwheel]
build-frontend = "build[uv]"
build = ["cp312-*", "cp315t-*"]
skip = "*-win32 *-manylinux_i686"
test-groups = ["dev"]
test-extras = ["numpy", "numba"]
test-command = "pytest {package}/tests"
before-build = ["git checkout uv.lock && git clean -fdx src/vspackrgb"]

[tool.cibuildwheel.windows]
archs = ["AMD64"]
test-groups = []
# https://github.com/pypa/cibuildwheel/pull/2978
before-test = 'uv pip install "pytest>=9.0.0,<10.0.0" vsjetengine>=1.8.0'

[tool.cibuildwheel.macos]
archs = ["native"]
# Matches minimum supported by VapourSynth
environment = { MACOSX_DEPLOYMENT_TARGET = "13.0" }

[tool.cibuildwheel.linux]
archs = ["native"]
before-all = "curl -sSf https://sh.rustup.rs | sh -s -- -y"
environment = { PATH = "$HOME/.cargo/bin:$PATH" }
# Matches minimum supported by VapourSynth
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"

[[tool.cibuildwheel.overrides]]
select = ["cp315t-*", "*-musllinux_*", "*-macosx_x86_64"]
test-extras = ["numpy"]
