def pack_bgra_8bit(
    b_ptr: int,
    g_ptr: int,
    r_ptr: int,
    a_ptr: int | None,
    width: int,
    height: int,
    src_stride: int,
    dest_ptr: int,
    dest_stride: int,
) -> None: ...
def pack_rgb30_10bit(
    r_ptr: int,
    g_ptr: int,
    b_ptr: int,
    a_ptr: int | None,
    width: int,
    height: int,
    samples_per_row: int,
    dest_ptr: int,
    dest_stride: int,
) -> None: ...
def pack_rgba64_16bit(
    r_ptr: int,
    g_ptr: int,
    b_ptr: int,
    a_ptr: int | None,
    width: int,
    height: int,
    samples_per_row: int,
    dest_ptr: int,
    dest_stride: int,
) -> None: ...
def pack_rgba16f_16bit(
    r_ptr: int,
    g_ptr: int,
    b_ptr: int,
    a_ptr: int | None,
    width: int,
    height: int,
    samples_per_row: int,
    dest_ptr: int,
    dest_stride: int,
) -> None: ...
def pack_rgba32f_32bit(
    r_ptr: int,
    g_ptr: int,
    b_ptr: int,
    a_ptr: int | None,
    width: int,
    height: int,
    samples_per_row: int,
    dest_ptr: int,
    dest_stride: int,
) -> None: ...
